repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-case-conflict
        name: Check for files with names that would conflict on a case-insensitive filesystem
        entry: check-case-conflict
      - id: check-merge-conflict
        name: Check for files that contain merge conflict strings
        entry: check-merge-conflict
      - id: end-of-file-fixer
        name: Makes sure files end in a newline and only a newline.
        entry: end-of-file-fixer
        types: [text]
      - id: trailing-whitespace
        name: Trims trailing whitespace.
        entry: trailing-whitespace-fixer
        types: [text]
      - id: check-docstring-first
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff-format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff
        args: [--fix]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        exclude: ^(.venv/)
        types: [ python ]
